ec-europa/ecl-twig

src/ec/.storybook/webpack.config.js, src/ec/packages/ec-component-icon/__snapshots__/icon.test.js.snap, src/ec/packages/ec-component-icon/icon.story.js, src/ec/packages/ec-component-icon/icon.test.js, src/ec/packages/ec-component-icon/package.json
Hi guys, we made a couple of commits with a few changes for the icon component to be properly demoed in storybook and we fixed what was needed, mainly the test file.
We are giving you this to review so that you can see how close you were to get this component properly defined, thanks a lot for the work and yes, if this was a first use case to base the next iterations on other components on, now you have a reliable vision of what we expect out of any additional component.
You can merge this and then we will merge your pull request to master, this is only happening now in the context of this first component, after this you will take care of fixing what needed on existing pr.
Thanks again!
=> fix: (icon) - Applying fixes to the icon component to get it rendered in storybook

.eslintrc.js, src/ec/.storybook/manager-head.html, utils/storybook-addon-code/src/index.js, utils/storybook-addon-code/src/register.jsx
Add new "Show raw" button in the HTML panel
=> chore: show raw html

src/ec/packages/ec-component-accordion/.npmignore, src/ec/packages/ec-component-accordion/README.md, src/ec/packages/ec-component-accordion/__snapshots__/accordion.test.js.snap, src/ec/packages/ec-component-accordion/accordion.html.twig, src/ec/packages/ec-component-accordion/accordion.story.js, src/ec/packages/ec-component-accordion/accordion.test.js, src/ec/packages/ec-component-accordion/demo/data.js, src/ec/packages/ec-component-accordion/docs/accordion.md, src/ec/packages/ec-component-accordion/package.json, src/ec/packages/ec-components/package.json, yarn.lock
=> feat: EC component accordion - INNO-1344

src/ec/packages/ec-component-accordion/__snapshots__/accordion.test.js.snap, src/ec/packages/ec-component-button/button.html.twig, src/ec/packages/ec-component-expandable/__snapshots__/expandable.test.js.snap, src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
This PR removes unnecessary dashes in the button template + it fixes a leak in the includes.
Jira: INNO-1359
=> feat(button): improve quality, fix leak

src/ec/packages/ec-component-button/button.test.js, src/ec/packages/ec-component-card/__snapshots__/card.test.js.snap, src/ec/packages/ec-component-card/card.html.twig, src/ec/packages/ec-component-card/card.test.js, src/ec/packages/ec-component-card/package.json, yarn.lock
=> refactor(card): improve quality

src/ec/packages/ec-component-footer/__snapshots__/footer.test.js.snap, src/ec/packages/ec-component-footer/footer.html.twig, src/ec/packages/ec-component-footer/footer.test.js, src/ec/packages/ec-component-link/link.test.js
=> refactor(footer): improve quality

src/ec/packages/ec-component-blockquote/__snapshots__/blockquote.test.js.snap, src/ec/packages/ec-component-blockquote/blockquote.test.js, src/ec/packages/ec-component-blockquote/package.json, yarn.lock
Not much to improve here.
Jira: INNO-1357
=> refactor(blockquote): update dependency

src/ec/packages/ec-component-search-form/__snapshots__/search-form.test.js.snap, src/ec/packages/ec-component-search-form/package.json, src/ec/packages/ec-component-search-form/search-form.html.twig, src/ec/packages/ec-component-search-form/search-form.test.js, yarn.lock
=> refactor(search-form): improve quality

.eslintrc.js, src/ec/packages/ec-component-accordion/accordion.story.js, src/ec/packages/ec-component-breadcrumb/breadcrumb.story.js, src/ec/packages/ec-component-contextual-navigation/contextual-navigation.story.js, src/ec/packages/ec-component-expandable/expandable.story.js, src/ec/packages/ec-component-file/file.story.js, utils/storybook-addon-code/src/index.js
=> fix: use appendChild instead of append for IE/Edge

src/ec/packages/ec-component-icon/icon.html.twig, src/ec/packages/ec-component-icon/package.json, yarn.lock
- improve code
- update dependencies version
=> fix(icon): improve component - INNO-1408

src/ec/packages/ec-component-expandable/__snapshots__/expandable.test.js.snap, src/ec/packages/ec-component-expandable/expandable.html.twig, src/ec/packages/ec-component-expandable/expandable.test.js, src/ec/packages/ec-component-expandable/package.json
- fix versions
- fix parameters leak
- add tests
=> fix(expandable): improve component - INNO-1407

src/ec/packages/ec-component-hero-banner/__snapshots__/hero-banner.test.js.snap, src/ec/packages/ec-component-hero-banner/hero-banner.html.twig, src/ec/packages/ec-component-hero-banner/hero-banner.test.js, src/ec/packages/ec-component-page-banner/page-banner.html.twig
Improve component hero banner:
- remove unused dashes
- improve code
- add tests
=> refactor(hero-banner): improve component - INNO-1374

src/ec/packages/ec-component-language-list/.npmignore, src/ec/packages/ec-component-language-list/README.md, src/ec/packages/ec-component-language-list/docs/overlay.md, src/ec/packages/ec-component-language-list/docs/splash.md, src/ec/packages/ec-component-language-list/language-list-item.html.twig, src/ec/packages/ec-component-language-list/language-list-overlay.html.twig, src/ec/packages/ec-component-language-list/language-list-splash.html.twig, src/ec/packages/ec-component-language-list/language-list.html.twig, src/ec/packages/ec-component-language-list/language-list.story.js, src/ec/packages/ec-component-language-list/language-list.test.js
Align Twig component with React one (same file structure)
=> refactor(language-list): improve component - INNO-1426

docs/release.md
The docs should be complete now :)
=> docs: add "github release" step

src/ec/packages/ec-component-language-list/language-list.html.twig
=> fix: INNO-1553 change .length to |length

src/ec/.storybook/config.js
=> chore: INNO-1542 hide contextual nav component

src/ec/packages/ec-component-radio/README.md, src/ec/packages/ec-component-radio/__snapshots__/radio.test.js.snap, src/ec/packages/ec-component-radio/radio-button.html.twig
=> feat(radio): add checked parameter - INNO-1540

src/ec/packages/ec-component-inpage-navigation/.npmignore, src/ec/packages/ec-component-inpage-navigation/README.md, src/ec/packages/ec-component-inpage-navigation/__snapshots__/inpage-navigation.test.js.snap, src/ec/packages/ec-component-inpage-navigation/demo/data.js, src/ec/packages/ec-component-inpage-navigation/demo/page-filler.js, src/ec/packages/ec-component-inpage-navigation/docs/inpage-navigation.md, src/ec/packages/ec-component-inpage-navigation/inpage-navigation.html.twig, src/ec/packages/ec-component-inpage-navigation/inpage-navigation.story.js, src/ec/packages/ec-component-inpage-navigation/inpage-navigation.test.js, src/ec/packages/ec-component-inpage-navigation/package.json, src/ec/packages/ec-component-link/link.html.twig, src/ec/packages/ec-components/package.json, yarn.lock
=> feat: implement inpage navigation - INNO-1555

src/ec/packages/ec-component-description-list/.npmignore, src/ec/packages/ec-component-description-list/README.md, src/ec/packages/ec-component-description-list/__snapshots__/description-list.test.js.snap, src/ec/packages/ec-component-description-list/description-list.html.twig, src/ec/packages/ec-component-description-list/description-list.story.js, src/ec/packages/ec-component-description-list/description-list.test.js, src/ec/packages/ec-component-description-list/package.json, src/ec/packages/ec-component-ordered-list/.npmignore, src/ec/packages/ec-component-ordered-list/README.md, src/ec/packages/ec-component-ordered-list/__snapshots__/ordered-list.test.js.snap, src/ec/packages/ec-component-ordered-list/ordered-list.html.twig, src/ec/packages/ec-component-ordered-list/ordered-list.story.js, src/ec/packages/ec-component-ordered-list/ordered-list.test.js, src/ec/packages/ec-component-ordered-list/package.json, src/ec/packages/ec-component-unordered-list/.npmignore, src/ec/packages/ec-component-unordered-list/README.md, src/ec/packages/ec-component-unordered-list/__snapshots__/unordered-list.test.js.snap, src/ec/packages/ec-component-unordered-list/package.json, src/ec/packages/ec-component-unordered-list/unordered-list.html.twig, src/ec/packages/ec-component-unordered-list/unordered-list.story.js, src/ec/packages/ec-component-unordered-list/unordered-list.test.js, src/ec/packages/ec-components/package.json, yarn.lock
=> feat(list): implement List components - INNO-1541

src/ec/packages/ec-component-link/__snapshots__/link.test.js.snap, src/ec/packages/ec-component-link/link.story.js, src/ec/packages/ec-component-link/link.test.js
I haven't updated the component version. Guessing that this is an operation we only perform while "releasing".
=> feat(link): add CTA example - INNO-1627

src/ec/packages/ec-component-footer/__snapshots__/footer.test.js.snap, src/ec/packages/ec-component-footer/docs/footer.md, src/ec/packages/ec-component-footer/footer.html.twig
=> refactor(footer): hide back to top - INNO-1663

src/ec/packages/ec-component-search-form/docs/search-form.md, src/ec/packages/ec-component-search-form/search-form.html.twig
=> feat(search-from): add extra_blocks parameter - INNO-1665

src/ec/packages/ec-component-timeline/__snapshots__/timeline.test.js.snap, src/ec/packages/ec-component-timeline/timeline.html.twig
=> fix(timeline): wrap with condition div.ecl-timeline2__title - TWIG-13

src/ec/packages/ec-component-language-list/language-list-overlay.html.twig
=> fix(language-list-overlay): Missing </div> - TWIG-19

src/ec/packages/ec-component-search-form/__snapshots__/search-form.test.js.snap, src/ec/packages/ec-component-search-form/search-form.test.js
=> fix(search-form): add test with extra_from_elements - TWIG-11

src/ec/packages/ec-component-icon/docs/icon.md, src/ec/packages/ec-component-menu-legacy/__snapshots__/menu-legacy.test.js.snap, src/ec/packages/ec-component-menu-legacy/demo/data.js, src/ec/packages/ec-component-menu-legacy/docs/menu-legacy.md, src/ec/packages/ec-component-menu-legacy/menu-legacy.html.twig, src/ec/packages/ec-component-menu-legacy/menu-legacy.story.js, src/ec/packages/ec-component-menu-legacy/menu-legacy.test.js
=> feat(menu-legacy): 2.9.1 - Fixing twig template - Twig 44

src/ec/packages/ec-components/package.json
=> feat: (table) - 2.9.1  - Addding package in the list of components - TWIG-43

src/ec/packages/ec-component-icon/docs/icon.md, src/ec/packages/ec-component-menu-legacy/__snapshots__/menu-legacy.test.js.snap, src/ec/packages/ec-component-menu-legacy/demo/data.js, src/ec/packages/ec-component-menu-legacy/docs/menu-legacy.md, src/ec/packages/ec-component-menu-legacy/menu-legacy.html.twig, src/ec/packages/ec-component-menu-legacy/menu-legacy.story.js, src/ec/packages/ec-component-menu-legacy/menu-legacy.test.js, src/ec/packages/ec-components/package.json
=> chore: 2.9.1  TWIG release

src/ec/packages/ec-component-message/message.story.js
=> fix(messages): add knobs and review story to have only one - TWIG-55

src/ec/.storybook/config.js
=> fix(storybook): Fixing failure on hot reload

src/ec/packages/ec-component-inpage-navigation/inpage-navigation.story.js
=> fix(inpage-navigation): Add ecl heading and paragraphs classes to content - TWIG-61

src/ec/packages/ec-component-unordered-list/README.md, src/ec/packages/ec-component-unordered-list/__snapshots__/unordered-list.test.js.snap, src/ec/packages/ec-component-unordered-list/unordered-list.html.twig, src/ec/packages/ec-component-unordered-list/unordered-list.story.js, src/ec/packages/ec-component-unordered-list/unordered-list.test.js
=> feat(unordered-list): adding variant select in the story and logic in the template

src/ec/packages/ec-component-tag/tag.html.twig, src/ec/packages/ec-component-tag/tag.story.js
=> fix(tag): add missing button story for tag component - TWIG-62

src/ec/packages/ec-component-hero-banner/__snapshots__/hero-banner.test.js.snap, src/ec/packages/ec-component-hero-banner/hero-banner.html.twig
=> fix(hero-banner): review styling of cta link - TWIG-60

src/ec/.storybook/preview-head.html
=> chore(ecl-presets): Update legacy presets to 2.12

src/ec/packages/ec-component-card/card.html.twig
=> fix(card): render description only if it's not empty - TWIG-83

src/ec/packages/ec-component-table/table.html.twig
=> fix(table): add raw filter to cells attributes values - TWIG-84

composer.json, docs/getting-started.md, scripts/grump-dis.sh
=> fix(grump-php): Changing approach, maintaining grump-php

docs/getting-started.md
=> docs(getting-started): Updating minimal version of node.js - TWIG-90

src/ec/.storybook/preview-head.html
=> chore(ecl-presets): Update legacy presets to 2.14

src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.html.twig, src/ec/packages/ec-component-site-header-standardised/site-header-standardised.html.twig
=> feat(attributes): Escape values of attributes for siteHeaders - TWIG-105

src/ec/packages/ec-component-site-header-harmonised/README.md, src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap, src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.html.twig, src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js, src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.test.js
=> fix(site-header-harmonised): Add missing group class - TWIG-106

babel.config.js, package.json, utils/data-utils/src/index.js
=> chore(data-utils): Exporting in common.js syntax

src/ec/packages/ec-component-site-header-harmonised/README.md, src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap, src/ec/packages/ec-component-site-header-harmonised/demo/data.js, src/ec/packages/ec-component-site-header-harmonised/package.json, src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.html.twig, src/ec/packages/ec-component-site-header-standardised/README.md, src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap, src/ec/packages/ec-component-site-header-standardised/demo/data.js, src/ec/packages/ec-component-site-header-standardised/package.json, src/ec/packages/ec-component-site-header-standardised/site-header-standardised.html.twig, src/ec/packages/ec-components/package.json, yarn.lock
=> feat(site-headers): Render class name as a link - TWIG-104

src/ec/packages/ec-component-footer-harmonised/.npmignore, src/ec/packages/ec-component-footer-harmonised/CHANGELOG.md, src/ec/packages/ec-component-footer-harmonised/README.md, src/ec/packages/ec-component-footer-harmonised/__snapshots__/footer-harmonised.test.js.snap, src/ec/packages/ec-component-footer-harmonised/demo/data.js, src/ec/packages/ec-component-footer-harmonised/docs/footer-harmonised.md, src/ec/packages/ec-component-footer-harmonised/footer-harmonised.html.twig, src/ec/packages/ec-component-footer-harmonised/footer-harmonised.story.js, src/ec/packages/ec-component-footer-harmonised/footer-harmonised.test.js, src/ec/packages/ec-component-footer-harmonised/package.json, src/ec/packages/ec-component-footer-standardised/__snapshots__/footer-standardised.test.js.snap, src/ec/packages/ec-component-footer-standardised/docs/footer-standardised.md, src/ec/packages/ec-component-footer-standardised/footer-standardised.html.twig, src/ec/packages/ec-components/package.json, yarn.lock
PR replacement for existing https://github.com/ec-europa/ecl-twig/pull/197
=> feat(footer-harmonised): Add component - TWIG-74

.drone.yml, .eslintignore, package.json, scripts/set-netlify-deployment-status.js, yarn.lock
Drone pipeline has been converted from a matrix one to a regular one as there isn't a need for parallel testing at the moment.
Previews are build and published for all cases except push to master branch, whereas production is build and deployed on the latter.
=> chore(drone): deploy to netlify - INNO-1932

src/ec/.storybook/preview-head.html, src/ec/packages/ec-component-inpage-navigation/ecl-inpage-navigation.html.twig, src/ec/packages/ec-component-inpage-navigation/inpage-navigation.story.js, src/ec/packages/ec-component-inpage-navigation/package.json, src/ec/packages/ec-components/package.json, yarn.lock
=> fix(inpage-nav): remove sticky nav when out of viewport - TWIG-138

src/ec/packages/ec-component-link/__snapshots__/link.test.js.snap, src/ec/packages/ec-component-link/adapter.js, src/ec/packages/ec-component-link/demo/data--cta-icon.js, src/ec/packages/ec-component-link/demo/data--cta.js, src/ec/packages/ec-component-link/demo/data--default.js, src/ec/packages/ec-component-link/demo/data--icon.js, src/ec/packages/ec-component-link/demo/data--standalone.js, src/ec/packages/ec-component-link/link.story.js, src/ec/packages/ec-component-link/link.test.js
=> refactor(link): specs file, adapter, story and test adapted - TWIG-130

src/ec/packages/ec-component-text-area/README.md, src/ec/packages/ec-component-text-area/__snapshots__/text-area.test.js.snap, src/ec/packages/ec-component-text-area/adapter.js, src/ec/packages/ec-component-text-area/demo/data--default.js, src/ec/packages/ec-component-text-area/demo/data--has-error.js, src/ec/packages/ec-component-text-area/demo/data--is-disabled.js, src/ec/packages/ec-component-text-area/ecl-text-area.html.twig, src/ec/packages/ec-component-text-area/text-area.story.js, src/ec/packages/ec-component-text-area/text-area.test.js
=> refactor(text-area): Specs file, adapter, fixing missing required attr - TWIG-129

php/php_storybook/resources/fix-data.js, src/ec/packages/ec-component-tag/__snapshots__/tag.test.js.snap, src/ec/packages/ec-component-tag/demo/data--button.js, src/ec/packages/ec-component-tag/demo/data--link.js, src/ec/packages/ec-component-tag/demo/data--removable.js, src/ec/packages/ec-component-tag/tag.story.js, src/ec/packages/ec-component-tag/tag.test.js
=> refactor(tag): specs file, test and story adapted - TWIG-124

package.json, yarn.lock
=> fix(deps): Uprading serialize-javascript to get rid of warning - TWIG-166

src/ec/packages/ec-component-language-list/__snapshots__/language-list.test.js.snap, src/ec/packages/ec-component-language-list/ecl-language-list-overlay.html.twig, src/ec/packages/ec-component-language-list/package.json, src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap, src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap, src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap, src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap
=> feat(language-list): Icon removed - TWIG-165

package.json, yarn.lock
…duplicated version of istanbul-reports (#276)
=> fix(warning about handlebars): master to develop 

src/ec/.storybook/preview-head.html, src/ec/packages/ec-component-footer-harmonised/README.md, src/ec/packages/ec-component-footer-harmonised/__snapshots__/footer-harmonised.test.js.snap, src/ec/packages/ec-component-footer-harmonised/demo/data--group3.js, src/ec/packages/ec-component-footer-harmonised/ecl-footer-harmonised.html.twig, src/ec/packages/ec-component-footer-harmonised/footer-harmonised.story.js, src/ec/packages/ec-component-footer-harmonised/footer-harmonised.test.js, src/ec/packages/ec-component-footer-harmonised/package.json, yarn.lock
=> feat(footer-harmonised): Adding group3 - TWIG-202

php/php_storybook/resources/helpers.php, php/php_storybook/scripts/ecl-diff.js, php/php_storybook/scripts/render.js, src/ec/packages/ec-component-gallery/__snapshots__/gallery.test.js.snap, src/ec/packages/ec-component-gallery/demo/data.js, src/ec/packages/ec-component-gallery/ecl-gallery.html.twig, src/ec/packages/ec-component-gallery/ecl-video.html.twig
=> fix(gallery): fixing templates, removing fixes in the render scripts - TWIG-231

php/php_storybook/resources/helpers.php
=> fix(php-storybook): fixing grouping issues in the story files - TWIG-221

lerna.json
=> internal: changelog, applying same schema as ECL - TWIG-255

php/php_storybook/resources/helpers.php
=> fix(php-storybook): datepicker is in the form section - TWIG-256

src/ec/packages/ec-component-blockquote/blockquote.story.js
=> feat(knobs): Quick order change knobs blockquote - FRONT-458

src/ec/.storybook/preview-head.html, src/ec/packages/ec-component-file-upload/README.md, src/ec/packages/ec-component-file-upload/__snapshots__/file-upload.test.js.snap, src/ec/packages/ec-component-file-upload/adapter.js, src/ec/packages/ec-component-file-upload/demo/data--multiple.js, src/ec/packages/ec-component-file-upload/demo/data.js, src/ec/packages/ec-component-file-upload/ecl-file-upload.html.twig, src/ec/packages/ec-component-file-upload/file-upload.story.js, src/ec/packages/ec-component-file-upload/package.json, yarn.lock
=> fix(file-input): Updating component to 2.22.1 - FRONT-465

php/php_storybook/resources/fix-build.js
=> fix(php-storybook): English logo fixed - FRONT-484

src/ec/packages/ec-component-link/link.story.js
=> fix(link): Fixing cta story knobs - FRONT-487

src/ec/packages/ec-component-pagination/pagination.story.js
=> feat(Pagination): added knob Aria label - FRONT-488

src/ec/packages/ec-component-skip-link/README.md, src/ec/packages/ec-component-skip-link/__snapshots__/skip-link.test.js.snap, src/ec/packages/ec-component-skip-link/skip-link.story.js, src/ec/packages/ec-component-skip-link/skip-link.test.js
=> refactor(skip-link): Added knob, using specs in story and tests, tests updated - FRONT-489

src/ec/packages/ec-component-card/__snapshots__/card.test.js.snap, src/ec/packages/ec-component-card/card.story.js, src/ec/packages/ec-component-card/ecl-card.html.twig
There are tow known issues:
1.  The knobs in the other groups are not updated when the story is reloaded after the click on a button.
2. The buttons have the group label appended to their own labels. (storybook bug, apparently)
=> feat(knobs): Poc for a panel with three sub-panels, buttons for show/hiding - FRONT-813

src/ec/packages/ec-component-text-input/adapter.js, src/ec/packages/ec-component-text-input/text-input.story.js
=> refactor(demo): Text input, grouping knobs, adding states - FRONT-903

src/ec/packages/ec-component-radio/radio.story.js
=> refactor(demo): Radio, grouping knobs - FRONT-902

src/ec/packages/ec-component-file/file.story.js
=> refactor(demo): File, mandatory/optional knobs - FRONT-875

src/ec/packages/ec-component-checkbox/checkbox.story.js
=> refactor(demo): Checkbox, optional/mandatory knobs - FRONT-901

src/ec/packages/ec-component-date-block/date-block.story.js
=> refactor(demo): Date block, mandatory/optional knobs, added stories for statuses - FRONT-900

src/ec/packages/ec-component-checkbox/checkbox.story.js, src/ec/packages/ec-component-file/file.story.js, src/ec/packages/ec-component-radio/radio.story.js, src/ec/packages/ec-component-search-form/search-form.story.js, utils/story-utils/src/index.js
Since this pr contains an update of the story-utils plugin, in order to test it you need to remove the node_modules folder and run yarn or you can manually move the index.js file in the src folder of the story-utils plugin into the package in the node_modules folder.
=> refactor(demo): Form components alignment - FRONT-953

src/ec/packages/ec-component-button/button.story.js, src/ec/packages/ec-component-icon/adapter.js, src/ec/packages/ec-component-icon/demo/data--audio.js, src/ec/packages/ec-component-icon/demo/data--facebook.js, src/ec/packages/ec-component-icon/demo/data--success.js, src/ec/packages/ec-component-icon/demo/data--ui.js, src/ec/packages/ec-component-icon/icon.story.js, utils/story-utils/src/index.js
=> refactor(demo): Icon, optional/mandatory elements - FRONT-914

php/php_storybook/scripts/ecl-diff.js
=> fix(ecl-diff): Replacing decode-html with he - FRONT-958

php/php_storybook/scripts/ecl-diff.js, src/ec/packages/ec-component-language-list/__snapshots__/language-list.test.js.snap, src/ec/packages/ec-component-language-list/ecl-language-list.html.twig, src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap, src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig, src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap, src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig, src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap, src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig, src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap, src/ec/packages/ec-component-site-header/adapter.js, src/ec/packages/ec-component-site-header/ecl-site-header.html.twig, src/ec/packages/ec-component-site-header/site-header.story.js
=> fix(site-header): Setting overlay to true for the language list - FRONT-959

src/ec/packages/ec-component-social-media-follow/demo/data.js, src/ec/packages/ec-component-social-media-follow/ecl-social-media-follow.html.twig, src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js
This includes an update on the story-util plugin, you need to manually update it in the node_modules by copying the index.js file or rebuild entirely the node_modules folder by removing it and running yarn again.. ;)
=> refactor(demo): Social media follow, mandatory/optional knobs - FRONT-920

src/ec/packages/ec-component-site-header-core/site-header-core.story.js, src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap, src/ec/packages/ec-component-site-header-standardised/adapter.js, src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig, src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js, utils/story-utils/src/index.js
There is an update in the index.js of the story-utils package
=> refactor(demo): Site Header Standardised, mandatory/optional knobs - FRONT-919

src/ec/packages/ec-component-accordion/accordion.story.js
=> refactor(demo): Accordion knobs and labels added - FRONT 909

src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js, src/ec/packages/ec-component-social-media-share/demo/data.js, src/ec/packages/ec-component-social-media-share/ecl-social-media-share.html.twig, src/ec/packages/ec-component-social-media-share/social-media-share.story.js, utils/story-utils/src/index.js
=> refactor(demo): Social media share, optional/mandatory knobs - FRONT-921

src/ec/packages/ec-component-timeline/README.md, src/ec/packages/ec-component-timeline/__snapshots__/timeline.test.js.snap, src/ec/packages/ec-component-timeline/adapter.js, src/ec/packages/ec-component-timeline/demo/data.js, src/ec/packages/ec-component-timeline/ecl-timeline.html.twig, src/ec/packages/ec-component-timeline/timeline.story.js
=> fix(demo): Timeline, adding ids, reorganisation of some knobs - FRONT-972

src/ec/packages/ec-component-site-header-core/site-header-core.story.js, src/ec/packages/ec-component-site-header-harmonised/README.md, src/ec/packages/ec-component-site-header-harmonised/adapter.js, src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig, src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js, src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js, utils/story-utils/src/index.js
=> refactor(demo): Site header harmonised - Mandatory/optional knobs - FRONT-918

package.json, yarn.lock
=> fix(deps): Forcing version of minimalist - FRONT-1011

src/ec/packages/ec-component-file-upload/file-upload.story.js, utils/story-utils/src/index.js
=> refactor(demo): File upload, optiona/mandatory knobs - FRONT-1019

src/ec/packages/ec-component-description-list/description-list.story.js, src/ec/packages/ec-component-ordered-list/ordered-list.story.js, src/ec/packages/ec-component-unordered-list/unordered-list.story.js
=> refactor(demo): List, optional/mandatory knobs - FRONT-1020

src/ec/packages/ec-component-pagination/pagination.story.js
=> refactor(demo): Pagination, mandatory/optional knobs - FRONT-1018

src/ec/packages/ec-component-breadcrumb-core/breadcrumb-core.story.js, utils/story-utils/src/index.js
=> refactor(demo): Breadcrumb core, optional/mandatory knobs - FRONT-1015

src/ec/packages/ec-component-breadcrumb-standardised/breadcrumb-standardised.story.js, utils/story-utils/src/index.js
=> refactor(demo): Breadcrumb standardised - optional/mandatory knobs - FRONT-1016

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-form-group.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-radio.html.twig, src/ec/packages/ec-component-radio/README.md, src/ec/packages/ec-component-radio/__snapshots__/radio.test.js.snap, src/ec/packages/ec-component-radio/ecl-radio-button.html.twig, src/ec/packages/ec-component-radio/ecl-radio-group.html.twig, src/ec/packages/ec-component-radio/radio.story.js, src/ec/packages/ec-component-radio/radio.test.js
=> feat(ecl-compliance): Radio, adding child template - FRONT-1069

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-expandable.html.twig, src/ec/packages/ec-component-expandable/README.md, src/ec/packages/ec-component-expandable/__snapshots__/expandable.test.js.snap, src/ec/packages/ec-component-expandable/ecl-expandable.html.twig, src/ec/packages/ec-component-expandable/expandable.test.js
=> feat(ecl-compliance): Expandable, adding child template - FRONT-1071

src/ec/packages/ec-component-breadcrumb/__snapshots__/breadcrumb.test.js.snap, src/ec/packages/ec-component-breadcrumb/breadcrumb.story.js, src/ec/packages/ec-component-breadcrumb/breadcrumb.test.js, src/ec/packages/ec-component-breadcrumb/ecl-breadcrumb.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-breadcrumb.html.twig, src/ec/packages/ec-component-ecl-compliance/ecl-compliance.html.twig
=> feat(ecl-compliance): Breadcrumb, adding child template, adding optional/mandatory knobs - FRONT-1103

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-search-form.html.twig, src/ec/packages/ec-component-search-form/__snapshots__/search-form.test.js.snap, src/ec/packages/ec-component-search-form/ecl-search-form.html.twig, src/ec/packages/ec-component-search-form/search-form.story.js, src/ec/packages/ec-component-search-form/search-form.test.js
=> feat(ecl-compliance): Search form, adding child template - FRONT-1072

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-fact-figures.html.twig, src/ec/packages/ec-component-fact-figures/__snapshots__/fact-figures.test.js.snap, src/ec/packages/ec-component-fact-figures/ecl-fact-figures.html.twig, src/ec/packages/ec-component-fact-figures/fact-figures.story.js, src/ec/packages/ec-component-fact-figures/fact-figures.test.js
=> feat(ecl-compliance): Fact and figures, adding child template - FRONT-1077

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-form-group.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-text-input.html.twig, src/ec/packages/ec-component-text-input/__snapshots__/text-input.test.js.snap, src/ec/packages/ec-component-text-input/ecl-text-input.html.twig, src/ec/packages/ec-component-text-input/text-input.story.js, src/ec/packages/ec-component-text-input/text-input.test.js
=> feat(ecl-compliance): text-input, adding child template - FRONT-1064

src/ec/packages/ec-component-button/__snapshots__/button.test.js.snap, src/ec/packages/ec-component-button/button.story.js, src/ec/packages/ec-component-button/button.test.js, src/ec/packages/ec-component-button/ecl-button.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-button.html.twig, src/ec/packages/ec-component-ecl-compliance/package.json
=> feat(ecl-compliance): Button, adding child template - FRONT-1054

src/ec/packages/ec-component-checkbox/README.md, src/ec/packages/ec-component-checkbox/__snapshots__/checkbox.test.js.snap, src/ec/packages/ec-component-checkbox/checkbox.story.js, src/ec/packages/ec-component-checkbox/checkbox.test.js, src/ec/packages/ec-component-checkbox/ecl-checkbox-button.html.twig, src/ec/packages/ec-component-checkbox/ecl-checkbox-group.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-checkbox.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-form-group.html.twig
=> feat(ecl-compliance): Checkbox, adding child template - FRONT-1068

src/ec/packages/ec-component-blockquote/__snapshots__/blockquote.test.js.snap, src/ec/packages/ec-component-blockquote/blockquote.story.js, src/ec/packages/ec-component-blockquote/blockquote.test.js, src/ec/packages/ec-component-blockquote/ecl-blockquote.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-blockquote.html.twig
=> feat(ecl-compliance): Blockquote, adding child template - FRONT-1053

src/ec/packages/ec-component-button/__snapshots__/button.test.js.snap, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-message.html.twig, src/ec/packages/ec-component-expandable/__snapshots__/expandable.test.js.snap, src/ec/packages/ec-component-message/__snapshots__/message.test.js.snap, src/ec/packages/ec-component-message/ecl-message.html.twig, src/ec/packages/ec-component-message/message.story.js, src/ec/packages/ec-component-message/message.test.js
=> feat(ecl-compliance): message, adding child template - FRONT-1093

src/ec/.storybook/preview-head.html, src/ec/packages/ec-component-page-header/README.md, src/ec/packages/ec-component-page-header/__snapshots__/page-header.test.js.snap, src/ec/packages/ec-component-page-header/adapter.js, src/ec/packages/ec-component-page-header/demo/data--background-image.js, src/ec/packages/ec-component-page-header/ecl-page-header.html.twig, src/ec/packages/ec-component-page-header/package.json, src/ec/packages/ec-component-page-header/page-header.story.js, src/ec/packages/ec-component-page-header/page-header.test.js, yarn.lock
=> feat(page-header): Adding background-image variant

src/ec/packages/ec-component-breadcrumb-standardised/README.md, src/ec/packages/ec-component-breadcrumb-standardised/__snapshots__/breadcrumb-standardised.test.js.snap, src/ec/packages/ec-component-breadcrumb-standardised/breadcrumb-standardised.story.js, src/ec/packages/ec-component-breadcrumb-standardised/breadcrumb-standardised.test.js, src/ec/packages/ec-component-breadcrumb-standardised/ecl-breadcrumb-standardised.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-breadcrumb.html.twig
Generic ecl-compliance-breadcrumb used.
=> feat(ecl-compliance): Breadcrumb standardised, adding child template - FRONT-1105

src/ec/packages/ec-component-breadcrumb-harmonised/README.md, src/ec/packages/ec-component-breadcrumb-harmonised/__snapshots__/breadcrumb-harmonised.test.js.snap, src/ec/packages/ec-component-breadcrumb-harmonised/breadcrumb-harmonised.story.js, src/ec/packages/ec-component-breadcrumb-harmonised/breadcrumb-harmonised.test.js, src/ec/packages/ec-component-breadcrumb-harmonised/ecl-breadcrumb-harmonised.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-breadcrumb.html.twig
=> feat(ecl-compliance): Breadcrumb harmonised, adding child template - FRONT-1106

src/ec/packages/ec-component-language-list/README.md, src/ec/packages/ec-component-language-list/ecl-language-list-grid.html.twig, src/ec/packages/ec-component-language-list/ecl-language-list-item.html.twig, src/ec/packages/ec-component-language-list/ecl-language-list.html.twig
=> fix(language-list): Adding checks for props - FRONT-1143

src/ec/packages/ec-component-button/ecl-button.html.twig
=> fix(button): Using local variable _disabled - FRONT-1139

src/ec/packages/ec-component-menu/__snapshots__/menu.test.js.snap, src/ec/packages/ec-component-menu/ecl-menu.html.twig
=> fix(menu): using local variables - FRONT-1140

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-icon.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-social-media.html.twig, src/ec/packages/ec-component-icon/__snapshots__/icon.test.js.snap, src/ec/packages/ec-component-link/__snapshots__/link.test.js.snap, src/ec/packages/ec-component-social-media-follow/README.md, src/ec/packages/ec-component-social-media-follow/__snapshots__/social-media-follow.test.js.snap, src/ec/packages/ec-component-social-media-follow/ecl-social-media-follow.html.twig, src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js, src/ec/packages/ec-component-social-media-follow/social-media-follow.test.js
=> feat(ecl-compliance): Social Media Follow, adding child template - FRONT-1094

src/ec/packages/ec-component-gallery/__snapshots__/gallery.test.js.snap, src/ec/packages/ec-component-gallery/ecl-gallery-item.html.twig, src/ec/packages/ec-component-gallery/ecl-gallery-overlay.html.twig, src/ec/packages/ec-component-gallery/ecl-gallery.html.twig
=> fix(gallery): Adding checks for props - FRONT-1141

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-icon.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-social-media.html.twig, src/ec/packages/ec-component-icon/__snapshots__/icon.test.js.snap, src/ec/packages/ec-component-link/__snapshots__/link.test.js.snap, src/ec/packages/ec-component-social-media-share/README.md, src/ec/packages/ec-component-social-media-share/__snapshots__/social-media-share.test.js.snap, src/ec/packages/ec-component-social-media-share/ecl-social-media-share.html.twig, src/ec/packages/ec-component-social-media-share/social-media-share.story.js, src/ec/packages/ec-component-social-media-share/social-media-share.test.js
=> feat(ecl-compliance): Social Media Share, adding child template - FRONT-1095

src/ec/packages/ec-component-accordion2/README.md, src/ec/packages/ec-component-accordion2/__snapshots__/accordion2.test.js.snap, src/ec/packages/ec-component-accordion2/accordion2.story.js, src/ec/packages/ec-component-accordion2/accordion2.test.js, src/ec/packages/ec-component-accordion2/ecl-accordion2.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-accordion.html.twig
=> feat(ecl-compliance): Accordion2, adding child template - FRONT-1052

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-media-container.html.twig, src/ec/packages/ec-component-media-container/README.md, src/ec/packages/ec-component-media-container/__snapshots__/media-container.test.js.snap, src/ec/packages/ec-component-media-container/ecl-media-container.html.twig, src/ec/packages/ec-component-media-container/media-container.story.js, src/ec/packages/ec-component-media-container/media-container.test.js
=> feat(ecl-compliance): Media Container, adding child template - FRONT-1096

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-pagination.html.twig, src/ec/packages/ec-component-pagination/README.md, src/ec/packages/ec-component-pagination/__snapshots__/pagination.test.js.snap, src/ec/packages/ec-component-pagination/ecl-pagination.html.twig, src/ec/packages/ec-component-pagination/pagination.story.js, src/ec/packages/ec-component-pagination/pagination.test.js
=> feat(ecl-compliance): Pagination, adding child template - FRONT-1097

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-skip-link.html.twig, src/ec/packages/ec-component-skip-link/README.md, src/ec/packages/ec-component-skip-link/__snapshots__/skip-link.test.js.snap, src/ec/packages/ec-component-skip-link/ecl-skip-link.html.twig, src/ec/packages/ec-component-skip-link/skip-link.story.js, src/ec/packages/ec-component-skip-link/skip-link.test.js
=> feat(ecl-compliance): Skip link, adding child template - FRONT-1107

src/ec/packages/ec-component-date-block/__snapshots__/date-block.test.js.snap, src/ec/packages/ec-component-date-block/date-block.story.js, src/ec/packages/ec-component-date-block/date-block.test.js, src/ec/packages/ec-component-date-block/ecl-date-block.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-date-block.html.twig
=> feat(ecl-compliance): Date Block, adding child template - FRONT-1062

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-tag.html.twig, src/ec/packages/ec-component-tag/README.md, src/ec/packages/ec-component-tag/__snapshots__/tag.test.js.snap, src/ec/packages/ec-component-tag/ecl-tag.html.twig, src/ec/packages/ec-component-tag/tag.story.js, src/ec/packages/ec-component-tag/tag.test.js
=> feat(ecl-compliance): Tag, adding child template - FRONT-1076

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-form-group.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-select.html.twig, src/ec/packages/ec-component-select/README.md, src/ec/packages/ec-component-select/__snapshots__/select.test.js.snap, src/ec/packages/ec-component-select/ecl-select.html.twig, src/ec/packages/ec-component-select/select.story.js, src/ec/packages/ec-component-select/select.test.js
=> feat(ecl-compliance): Select, adding child template - FRONT-1067

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-form-group.html.twig, src/ec/packages/ec-component-text-area/README.md, src/ec/packages/ec-component-text-area/__snapshots__/text-area.test.js.snap, src/ec/packages/ec-component-text-area/ecl-text-area.html.twig, src/ec/packages/ec-component-text-area/text-area.story.js, src/ec/packages/ec-component-text-area/text-area.test.js
=> feat(ecl-compliance): Text-area, adding validation - FRONT-1066

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-file.html.twig, src/ec/packages/ec-component-file/README.md, src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap, src/ec/packages/ec-component-file/ecl-file.html.twig, src/ec/packages/ec-component-file/file.story.js, src/ec/packages/ec-component-file/file.test.js
=> feat(ecl-compliance): File, adding child template - FRONT-1074

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-page-header-standardised.html.twig, src/ec/packages/ec-component-page-header-standardised/README.md, src/ec/packages/ec-component-page-header-standardised/__snapshots__/page-header-standardised.test.js.snap, src/ec/packages/ec-component-page-header-standardised/ecl-page-header-standardised.html.twig, src/ec/packages/ec-component-page-header-standardised/page-header-standardised.story.js, src/ec/packages/ec-component-page-header-standardised/page-header-standardised.test.js
=> feat(ecl-compliance): Page Header Standardised - FRONT-1088

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-page-header-harmonised.html.twig, src/ec/packages/ec-component-page-header-harmonised/README.md, src/ec/packages/ec-component-page-header-harmonised/__snapshots__/page-header-harmonised.test.js.snap, src/ec/packages/ec-component-page-header-harmonised/ecl-page-header-harmonised.html.twig, src/ec/packages/ec-component-page-header-harmonised/page-header-harmonised.story.js, src/ec/packages/ec-component-page-header-harmonised/page-header-harmonised.test.js
=> feat(ecl-compliance): Page Header Harmonised, adding child template FRONT-1149

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-page-header-core.html.twig, src/ec/packages/ec-component-page-header-core/README.md, src/ec/packages/ec-component-page-header-core/__snapshots__/page-header-core.test.js.snap, src/ec/packages/ec-component-page-header-core/ecl-page-header-core.html.twig, src/ec/packages/ec-component-page-header-core/page-header-core.story.js, src/ec/packages/ec-component-page-header-core/page-header-core.test.js
=> feat(ecl-compliance): Page Header Core, adding child template - FRONT-1087

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-menu-legacy.html.twig, src/ec/packages/ec-component-menu-legacy/README.md, src/ec/packages/ec-component-menu-legacy/__snapshots__/menu-legacy.test.js.snap, src/ec/packages/ec-component-menu-legacy/ecl-menu-legacy.html.twig, src/ec/packages/ec-component-menu-legacy/menu-legacy.story.js, src/ec/packages/ec-component-menu-legacy/menu-legacy.test.js
=> feat(ecl-compliance): Menu legacy, adding child template - FRONT-1108

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-site-header.html.twig, src/ec/packages/ec-component-site-header/README.md, src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap, src/ec/packages/ec-component-site-header/ecl-site-header.html.twig, src/ec/packages/ec-component-site-header/site-header.story.js, src/ec/packages/ec-component-site-header/site-header.test.js, utils/story-utils/src/index.js
=> feat(ecl-compliance): Site Header (deprecated), adding knobs and child template - FRONT-1089

src/ec/packages/ec-component-dropdown-legacy/README.md, src/ec/packages/ec-component-dropdown-legacy/__snapshots__/dropdown-legacy.test.js.snap, src/ec/packages/ec-component-dropdown-legacy/demo/data.js, src/ec/packages/ec-component-dropdown-legacy/dropdown-legacy.story.js, src/ec/packages/ec-component-dropdown-legacy/dropdown-legacy.test.js, src/ec/packages/ec-component-dropdown-legacy/ecl-dropdown-legacy.html.twig, src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-dropdown-legacy.html.twig
=> feat(ecl-compliance): Dropdwon legacy, adding knobs and child template - FRONT-1102

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-footer-standardised.html.twig, src/ec/packages/ec-component-footer-standardised/README.md, src/ec/packages/ec-component-footer-standardised/__snapshots__/footer-standardised.test.js.snap, src/ec/packages/ec-component-footer-standardised/adapter.js, src/ec/packages/ec-component-footer-standardised/ecl-footer-standardised.html.twig, src/ec/packages/ec-component-footer-standardised/footer-standardised.story.js, src/ec/packages/ec-component-footer-standardised/footer-standardised.test.js, src/ec/packages/ec-component-tag/__snapshots__/tag.test.js.snap
=> feat(ecl-compliance): Footer standardised, adding child template - FRONT-1084

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-footer-harmonised.html.twig, src/ec/packages/ec-component-footer-harmonised/README.md, src/ec/packages/ec-component-footer-harmonised/__snapshots__/footer-harmonised.test.js.snap, src/ec/packages/ec-component-footer-harmonised/adapter.js, src/ec/packages/ec-component-footer-harmonised/ecl-footer-harmonised.html.twig, src/ec/packages/ec-component-footer-harmonised/footer-harmonised.story.js, src/ec/packages/ec-component-footer-harmonised/footer-harmonised.test.js
=> feat(ecl-compliance): Footer Harmonised, adding child template - FRONT-1085

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-page-header.html.twig, src/ec/packages/ec-component-page-header/README.md, src/ec/packages/ec-component-page-header/__snapshots__/page-header.test.js.snap, src/ec/packages/ec-component-page-header/ecl-page-header.html.twig, src/ec/packages/ec-component-page-header/page-header.story.js, src/ec/packages/ec-component-page-header/page-header.test.js
=> feat(ecl-compliance): Page Header, adding child template - FRONT-1086

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-timeline.html.twig, src/ec/packages/ec-component-timeline/README.md, src/ec/packages/ec-component-timeline/__snapshots__/timeline.test.js.snap, src/ec/packages/ec-component-timeline/ecl-timeline.html.twig, src/ec/packages/ec-component-timeline/timeline.story.js, src/ec/packages/ec-component-timeline/timeline.test.js
Due to the fact that this component has the usage page and the demo misaligned it was not possible to fully implement a validation for the timeline.
So only the "timestamp" as been taken into account, for now.
=> feat(ecl-compliance): Timeline, adding child template - FRONT-1079

src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap, src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig, src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap, src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig, src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.test.js, src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap, src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
=> fix(site-headers): Fixing <hr> element - FRONT-1226

src/ec/packages/ec-component-menu/.npmignore
=> fix(menu): Adding .npmignore file - FRONT-1227

php/ec/.storybook/webpack.config.js, src/ec/storybook/.storybook/webpack.config.js, src/eu/storybook/.storybook/webpack.config.js
=> feat(webpack): Alternative way to disable progressPlugin - FRONT-1251

.drone.yml
As we know this ticket is just for anticipating changes that we requested to be deployed, basically to keep a reference to the latest pipeline requested.
=> chore: update drone pipeline - FRONT-1255

src/ec/packages/ec-component-inpage-navigation/__snapshots__/inpage-navigation.test.js.snap, src/ec/packages/ec-component-inpage-navigation/ecl-inpage-navigation.html.twig, src/ec/packages/ec-component-inpage-navigation/package.json, yarn.lock
=> fix(inpage-navigation): removing hidden attribute - FRONT-1265

src/ec/packages/ec-component-hero-banner/hero-banner.story.js, src/ec/packages/ec-component-hero-banner/package.json, yarn.lock
=> feat(hero-banner): Making everything optional, fixing icon knob behaviour - front-1282

src/ec/storybook/.storybook/preview-head.html
=> feat(ecl): Updating resources to 2.31.0

src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-language-list.html.twig, src/ec/packages/ec-component-language-list/README.md, src/ec/packages/ec-component-language-list/__snapshots__/language-list.test.js.snap, src/ec/packages/ec-component-language-list/adapter.js, src/ec/packages/ec-component-language-list/ecl-language-list-grid.html.twig, src/ec/packages/ec-component-language-list/ecl-language-list.html.twig, src/ec/packages/ec-component-language-list/language-list.story.js, src/ec/packages/ec-component-language-list/language-list.test.js, src/ec/packages/ec-component-language-list/package.json, src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap, src/ec/packages/ec-component-site-header-core/adapter.js, src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig, src/ec/packages/ec-component-site-header-core/package.json, src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap, src/ec/packages/ec-component-site-header-harmonised/adapter.js, src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig, src/ec/packages/ec-component-site-header-harmonised/package.json, src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap, src/ec/packages/ec-component-site-header-standardised/adapter.js, src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig, src/ec/packages/ec-component-site-header-standardised/package.json, src/ec/packages/ec-component-site-header/__snapshots__/site-header.test.js.snap, yarn.lock
=> feat(language-list): Non EU languages support added - front-1302

src/ec/packages/ec-component-fact-figures/adapter.js, src/ec/packages/ec-component-file/README.md, src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap, src/ec/packages/ec-component-file/adapter.js, src/ec/packages/ec-component-file/demo/data--thumbnail.js, src/ec/packages/ec-component-file/ecl-file.html.twig, src/ec/packages/ec-component-file/file.story.js, src/ec/packages/ec-component-file/file.test.js, src/ec/packages/ec-component-file/package.json, yarn.lock
=> feat(file): Adding thumbnail variant - front-1303

src/ec/packages/ec-component-footer-core/README.md, src/ec/packages/ec-component-footer-core/__snapshots__/footer-core.test.js.snap, src/ec/packages/ec-component-footer-core/adapter.js, src/ec/packages/ec-component-footer-core/demo/eu-data.js, src/ec/packages/ec-component-footer-core/ecl-footer-core.html.twig, src/ec/packages/ec-component-footer-harmonised/README.md, src/ec/packages/ec-component-footer-harmonised/ecl-footer-harmonised.html.twig, src/ec/packages/ec-component-footer-standardised/README.md, src/ec/packages/ec-component-footer-standardised/__snapshots__/footer-standardised.test.js.snap, src/ec/packages/ec-component-footer-standardised/adapter.js, src/ec/packages/ec-component-footer-standardised/demo/eu-data.js, src/ec/packages/ec-component-footer-standardised/ecl-footer-standardised.html.twig
=> fix(footers): fixing logos in EU footers for php-storybook - front-1347

src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig, src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig, src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
=> feat(site-headers): Improving include code for language list - front-1480

docs/README.md, docs/documentation.md, docs/getting-started.md
=> feat(docs): Simplifying getting started, creating documentation - front-1492

src/ec/storybook/.storybook/preview-head.html, src/eu/storybook/.storybook/preview-head.html
=> feat(ecl): update resources to 2.32.0 - front-1561

src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap, src/ec/packages/ec-component-file/ecl-file.html.twig, src/ec/packages/ec-component-file/file.story.js, src/ec/packages/ec-component-file/file.test.js
=> fix(file): Fixing markup for the thumbnail variant - front-1594

src/ec/packages/ec-component-site-header-core/site-header-core.story.js, src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
=> fix(site-headers): Login box is optional in the three families - front-1592

src/ec/packages/ec-component-date-block/ecl-date-block.html.twig, src/ec/storybook/.storybook/preview-head.html, src/eu/storybook/.storybook/preview-head.html
=> chore(ecl): update ECL resoureces to 2.33.0 - front-1670

src/ec/packages/ec-component-breadcrumb-core/package.json, src/ec/packages/ec-component-breadcrumb-harmonised/package.json, src/ec/packages/ec-component-breadcrumb-standardised/package.json, src/ec/packages/ec-component-page-header-core/__snapshots__/page-header-core.test.js.snap, src/ec/packages/ec-component-page-header-core/adapter.js, src/ec/packages/ec-component-page-header-core/package.json, src/ec/packages/ec-component-page-header-harmonised/__snapshots__/page-header-harmonised.test.js.snap, src/ec/packages/ec-component-page-header-harmonised/adapter.js, src/ec/packages/ec-component-page-header-harmonised/package.json, src/ec/packages/ec-component-page-header-standardised/__snapshots__/page-header-standardised.test.js.snap, src/ec/packages/ec-component-page-header-standardised/adapter.js, src/ec/packages/ec-component-page-header-standardised/package.json, yarn.lock
=> chore(page-headers): Small alignment with ECL - front-1668

src/ec/packages/ec-component-menu/__snapshots__/menu.test.js.snap, src/ec/packages/ec-component-menu/ecl-menu-item.html.twig, src/ec/packages/ec-component-menu/package.json, src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap, src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap, yarn.lock
=> feat(menu): Adding css class - front-1667

src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap, src/ec/packages/ec-component-file/adapter.js, src/ec/packages/ec-component-file/package.json, yarn.lock
=> chore(file): Small alignment with ECL - front-1669

src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap, src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig, src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js, src/ec/packages/ec-component-site-header-standardised/site-header-standardised.test.js
=> fix(site-header-standardised): Fixing markup in case no menu is present - front-1693

src/ec/packages/ec-component-datepicker/README.md, src/ec/packages/ec-component-datepicker/__snapshots__/datepicker.test.js.snap, src/ec/packages/ec-component-datepicker/datepicker.story.js, src/ec/packages/ec-component-datepicker/demo/data.js, src/ec/packages/ec-component-datepicker/ecl-datepicker.html.twig
=> fix(datepicker): Opt in/out for autoinit, adding default value - front-1699

package.json, php/ec/package.json, php/eu/package.json
=> fix(php-storybook): Creating local packages for storybook - front-1703

src/ec/packages/ec-component-button/__snapshots__/button.test.js.snap, src/ec/packages/ec-component-button/button.test.js, src/ec/packages/ec-component-button/ecl-button.html.twig
=> fix(button): Disabled attribute was deleting the custom attributes set - front-1708

src/ec/storybook/.storybook/preview-head.html, src/eu/storybook/.storybook/preview-head.html
=> chore(storybook): Update ECL resources to 2.34.0 - front-1713

src/ec/packages/ec-component-icon/README.md, src/ec/packages/ec-component-icon/__snapshots__/icon.test.js.snap, src/ec/packages/ec-component-icon/ecl-icon.html.twig, src/ec/packages/ec-component-icon/icon.test.js
=> feat(icon): Adding extra markup for accessibility - front-1715

src/ec/packages/ec-component-page-header/demo/eu-data--homepage-image.js
=> fix(page-header): homepage image variant doesn't have the breadcrumb - front-1727

.nvmrc, src/ec/storybook/.storybook/preview-head.html, src/eu/storybook/.storybook/preview-head.html, yarn.lock
=> chore(ECL): Upgrading ECL resources to 2.35.0 - FRONT-1820

src/ec/packages/ec-component-pagination/ecl-pagination.html.twig
=> fix(pagination): Fixing icon_path parameter usage - FRONT-1920

src/ec/packages/ec-component-gallery/ecl-gallery-item.html.twig
=> fix(gallery): description is optional - front-2061

package.json, php/ec/package.json, php/eu/package.json, src/ec/storybook/package.json, src/eu/storybook/package.json, utils/ecl-diff/package.json, utils/storybook-addon-notes/package.json, yarn.lock
=> chore(deps): Safe updates 07.06.21

package.json, php/ec/package.json, php/eu/package.json, src/ec/storybook/package.json, src/eu/storybook/package.json, utils/storybook-addon-code/package.json, utils/storybook-addon-diff/package.json, utils/storybook-addon-ecl-diff/package.json, utils/storybook-addon-jscode/package.json, utils/storybook-addon-notes/package.json, utils/storybook-addon-system-switcher/package.json, yarn.lock
=> chore(deps): updates 17-08-21
