ec-europa/ecl-twig

- src/ec/.storybook/config.js
- src/ec/.storybook/preview-head.html
- src/ec/packages/ec-component-icon/__snapshots__/icon.test.js.snap
- src/ec/packages/ec-component-icon/package.json
- src/eu/.storybook/config.js
- src/eu/.storybook/preview-head.html
- src/eu/packages/eu-component-icon/package.json
- yarn.lock
Use latest version of ECl (2.1.0).
Components already merged have been updated (only icons currently)
> chore: update to ECL 2.1.0

- docs/README.md
- docs/conventions.md
- docs/decisions/001-strip-whitespaces.md
- package.json
- src/ec/packages/ec-component-button/__snapshots__/button.test.js.snap
- src/ec/packages/ec-component-button/button.test.js
- src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
- src/ec/packages/ec-component-icon/icon.html.twig
- src/ec/packages/ec-component-link/__snapshots__/link.test.js.snap
- src/ec/packages/ec-component-link/link.html.twig
- src/ec/packages/ec-component-link/link.test.js
- src/ec/packages/ec-component-select/__snapshots__/select.test.js.snap
- src/ec/packages/ec-component-select/select.html.twig
- src/ec/packages/ec-component-select/select.test.js
- utils/test-utils/index.js
Without the `only` keyword on includes and embeds, the context leaks and since we use the same `extra_classes` and `extra_attributes` everywhere, all the templates in the cascade can read them!
TODO:
> docs: use `only` keyword

- src/ec/packages/ec-component-gallery/gallery.html.twig
- src/ec/packages/ec-component-language-list/language-list-overlay.html.twig
- src/ec/packages/ec-component-language-list/language-list-splash.html.twig
- src/ec/packages/ec-component-language-list/language-list.html.twig
- src/ec/packages/ec-component-radio/radio-group.html.twig
Sorry for the confusion, i created the branch and named the commit using the DTTSB label instead of INNO.. :)
> fix: change the way we load sub-components - INNO-1550

- src/ec/packages/ec-component-file/__snapshots__/file.test.js.snap
- src/ec/packages/ec-component-file/demo/data.js
- src/ec/packages/ec-component-file/docs/file.md
- src/ec/packages/ec-component-file/file.html.twig
- src/ec/packages/ec-component-file/file.story.js
New `download` property added to `translation.items`. This new property lets you define a custom label and href for each translation.
For convenience, there's also a new `icon_path` property which defaults to `icon.path` in order to avoid breaking changes. This new property is used for the icons that can not be changed (e.g. the download icons, the arrow icon)
> feat(file): add download link per translation - INNO-1581

- src/ec/packages/ec-component-card/__snapshots__/card.test.js.snap
- src/ec/packages/ec-component-card/card.html.twig
- src/ec/packages/ec-component-card/card.story.js
- src/ec/packages/ec-component-card/card.test.js
- src/ec/packages/ec-component-card/docs/card.md
Adding image alternate text variable to ec-component-card.
> fix: INNO-1696 Alt is not trigger on ec-component-card.

- src/ec/packages/ec-component-search-form/search-form.html.twig
- src/ec/packages/ec-component-search-form/search-form.story.js
- src/ec/packages/ec-component-text-area/docs/text-area.md
- src/ec/packages/ec-component-text-area/text-area.html.twig
- src/ec/packages/ec-component-text-area/text-area.test.js
- src/ec/packages/ec-component-text-input/__snapshots__/text-input.test.js.snap
- src/ec/packages/ec-component-text-input/docs/text-input.md
- src/ec/packages/ec-component-text-input/text-input.html.twig
- src/ec/packages/ec-component-text-input/text-input.test.js
> feat(text-input): adding extra classes for label, renaming prop TWIG-52

- src/ec/packages/ec-component-accordion/accordion.story.js
- src/ec/packages/ec-component-footer/footer.story.js
- src/ec/packages/ec-component-site-header/site-header.story.js
I opted for grouping the deprecated components all together, now that we have three, it would otherwise start to be terribly confusing.
So in storybook you will now find footer, accordion and site-header in a common "folder" named "deprecated". 
> feat(deprecated): old site header and footer are now deprecated

- src/ec/packages/ec-component-tag/__snapshots__/tag.test.js.snap
- src/ec/packages/ec-component-tag/tag.html.twig
- src/ec/packages/ec-component-tag/tag.story.js
> fix(tag): fix markup for removable tags - TWIG-78

- src/ec/packages/ec-component-menu-harmonised/menu-harmonised.story.js.bckp
- src/ec/packages/ec-component-menu-standardised/menu-standardised.story.js.bckp
- src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js.bckp
- src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js.bckp
> fix(hide-not-ready-components): Hiding site headers containing a menu - TWIG-161

- src/ec/packages/ec-component-menu/ecl-menu.html.twig
> fix(menu): href attribute needs quotes - TWIG-187

- package.json
- yarn.lock
The warning is about handlebars < 4.3.0, the investigation revealed that is the package "istanbul-reports" (as part of the jest dependencies) that was depending on an old version of handlebars.
together with some updates in the libraries a "resolutions" block has been added in the package.json, other attempts to upgrade istanbul-reports resulted in a duplicated version of the package that i could not ged rid of (using yarn-deduplicate or yarn-dedupe).
I don't think there is a way to "test" this on github to see whether the warning would go away, anyway you can look at the yarn.lock (might be needed to remove it, first) for handlebars, no older version than 4.3.0 should be in use, basically.
> fix(deps): Updating some deps, using resolutions block to get rid of duplicated version of istanbul-reports

- php/php_storybook/composer.json
- php/php_storybook/package.json
- src/ec/packages/ec-component-footer-harmonised/__snapshots__/footer-harmonised.test.js.snap
- src/ec/packages/ec-component-site-header-core/__snapshots__/site-header-core.test.js.snap
- src/ec/packages/ec-component-site-header-core/ecl-site-header-core.html.twig
- src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
- src/ec/packages/ec-component-site-header-standardised/ecl-site-header-standardised.html.twig
> fix(site-headers): Icons size reviewed - TWIG-201

- php/php_storybook/scripts/ecl-diff.js
This started as a specific fix on the issue mentioned in the issue's title but i took the chance to fix many other issues while doing this, i hope with this we are close to a "final" version of this script (we will have to maintain it everytim eECL changes something in the storybook organisation, unfotunately).
> fix(ecl-diff): Browsing Ecl website with puppeteer - TWIG-235

- src/ec/packages/ec-component-datepicker/datepicker.story.js
- src/ec/packages/ec-component-timeline/timeline.story.js
> refactor(knobs): Datepicker - Mandatory/optional knobs -  FRONT-905

- src/ec/packages/ec-component-language-list/adapter.js
- src/ec/packages/ec-component-language-list/demo/data--overlay.js
- src/ec/packages/ec-component-language-list/demo/data--splash.js
- src/ec/packages/ec-component-language-list/ecl-language-list-item.html.twig
- src/ec/packages/ec-component-language-list/language-list.story.js
- utils/storybook-addon-notes/src/index.js
These are changes that were lost from a previous pr where i probably forgot to push the right file, these changes are fixing also the output in the notes of components like social media share and language list where we give the possibility the delete item by unsetting them through the knobs.
The output in the notes tab if you choose "none" as the label of an item should be clean, the item is removed from the demo and the include code doesn't contain the item.
The same happens also in the social mendia components, if you remove an icon the item is removed as well and in the notes tab the output of the include code should be clean.
> refactor(demo): Language list, optional/mandatory knobs, fixing the notes plugin - FRONT-925

- src/ec/.storybook/preview-head.html
- src/ec/packages/ec-component-menu/README.md
- src/ec/packages/ec-component-menu/__snapshots__/menu.test.js.snap
- src/ec/packages/ec-component-menu/adapter.js
- src/ec/packages/ec-component-menu/ecl-menu-item.html.twig
- src/ec/packages/ec-component-menu/ecl-menu.html.twig
- src/ec/packages/ec-component-menu/menu.story.js
- src/ec/packages/ec-component-menu/package.json
- src/ec/packages/ec-component-site-header-harmonised/__snapshots__/site-header-harmonised.test.js.snap
- src/ec/packages/ec-component-site-header-harmonised/adapter.js
- src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
- src/ec/packages/ec-component-site-header-standardised/__snapshots__/site-header-standardised.test.js.snap
- yarn.lock
To reproduce the diff with the ECL markup:
render the component
`yarn check:component ec menu`
run the ecl-diff script:
`yarn ecl-diff ec`
the choiches you have to make are:
- "menu as the component
- "en" as the twig variant
- choose "navigation" from the subsections
You get it ;)
> feat(menuV2): Implementation, green diff with ECL - FRONT-991

- .gitignore
- composer.json
- docs/getting-started.md
- package.json
- scripts/grump-dis.js
- scripts/grump-dis.sh
- scripts/grump-en.js
- scripts/pre-commit.combined
- scripts/pre-commit.husky
- src/ec/packages/ec-component-site-header-harmonised/ecl-site-header-harmonised.html.twig
So, the logic here is:
We now have a way to combine grumphp and husky, we first execute grump-php and basing on its output we run or not the husky pre-commit script.
This way we prevent the commit from happening when there is an issue in one of our templates, the whole library is checked and not only the "staged" files which would normally happen using the pre-commit hook provided by grump-php, but the total number of files to be checked is really small, so it's not a performance issue.
The grump-en and grump-dis scripts have been replaced by node scripts and can be executed through yarn, the documentation has been updated.
To configure you environment:
`composer update`
`yarn grump-en`
Should be enough, you should …
> fix(pre-commit): Different approach for combining husky and grump-php - FRONT-960

- src/ec/packages/ec-component-table/README.md
- src/ec/packages/ec-component-table/__snapshots__/table.test.js.snap
- src/ec/packages/ec-component-table/ecl-table.html.twig
- src/ec/packages/ec-component-table/table.story.js
There is a problem with the notes panel, basically for the way we set in the data the extra_attributes and extra-classes for the rows, when we go rendering that in the panel we lose these information.
> refactor(knobs): table optional/mandatory knobs - FRONT-924

- src/ec/packages/ec-component-gallery/ecl-gallery-overlay.html.twig
- src/ec/packages/ec-component-gallery/ecl-gallery.html.twig
- src/ec/packages/ec-component-gallery/gallery.story.js
> refactor(knobs): Gallery optional/mandatory knobs -FRONT-926

- src/ec/packages/ec-component-accordion/accordion.story.js
- src/ec/packages/ec-component-accordion2/accordion2.story.js
- src/ec/packages/ec-component-button/button.story.js
- src/ec/packages/ec-component-checkbox/checkbox.story.js
- src/ec/packages/ec-component-datepicker/datepicker.story.js
- src/ec/packages/ec-component-file/file.story.js
- src/ec/packages/ec-component-gallery/gallery.story.js
- src/ec/packages/ec-component-hero-banner/hero-banner.story.js
- src/ec/packages/ec-component-icon/icon.story.js
- src/ec/packages/ec-component-inpage-navigation/inpage-navigation.story.js
- src/ec/packages/ec-component-language-list/language-list.story.js
- src/ec/packages/ec-component-menu/menu.story.js
- src/ec/packages/ec-component-message/message.story.js
- src/ec/packages/ec-component-page-banner/page-banner.story.js
- src/ec/packages/ec-component-radio/radio.story.js
- src/ec/packages/ec-component-search-form/search-form.story.js
- src/ec/packages/ec-component-select/select.story.js
- src/ec/packages/ec-component-site-header-core/site-header-core.story.js
- src/ec/packages/ec-component-site-header-harmonised/site-header-harmonised.story.js
- src/ec/packages/ec-component-site-header-standardised/site-header-standardised.story.js
- src/ec/packages/ec-component-social-media-follow/social-media-follow.story.js
- src/ec/packages/ec-component-social-media-share/social-media-share.story.js
- src/ec/packages/ec-component-table/table.story.js
- src/ec/packages/ec-component-tag/tag.story.js
- src/ec/packages/ec-component-timeline/timeline.story.js
- utils/story-utils/src/index.js
> refactor(utils): tabLabels instead of buttonLabels - FRONT-962

- src/ec/packages/ec-component-expandable/adapter.js
- src/ec/packages/ec-component-expandable/demo/data.js
- src/ec/packages/ec-component-expandable/ecl-expandable.html.twig
- src/ec/packages/ec-component-expandable/expandable.story.js
> refactor(demo): Expandable, optional.mandatory knobs - FRONT-1021

- src/ec/packages/ec-component-card/ecl-card.html.twig
> fix(card): Adding checks on props - FRONT-1138

- src/ec/packages/ec-component-radio/ecl-radio-button.html.twig
> fix(radio): Initializing local _extra_attributes variable - FRONT-1144

- src/ec/.storybook/preview-head.html
- src/ec/packages/ec-component-gallery/README.md
- src/ec/packages/ec-component-gallery/__snapshots__/gallery.test.js.snap
- src/ec/packages/ec-component-gallery/demo/data.js
- src/ec/packages/ec-component-gallery/ecl-gallery-overlay.html.twig
- src/ec/packages/ec-component-gallery/ecl-gallery.html.twig
- src/ec/packages/ec-component-gallery/package.json
- yarn.lock
Component aligned with ecl 2.29.0.
It is possible to retrieve the diff between our rendered html and the ecl one:
`yarn check:component ec gallery`
`yarn ecl-diff ec`, 
choose gallery, all the other options are already fine, just skip them.
> feat(gallery): Component and resources updates for v2.29.0 - FRONT-1222

- babel.config.js
- package.json
- src/ec/packages/ec-component-table/table.test.js
- yarn.lock
Adds `@babel/plugin-transform-runtime` plugin on a project level in order to enable async/await syntax.
> chore(babel): enable async/await

- src/ec/packages/ec-component-table/README.md
- src/ec/packages/ec-component-table/__snapshots__/table.test.js.snap
- src/ec/packages/ec-component-table/demo/data--default.js
- src/ec/packages/ec-component-table/demo/data--multi.js
- src/ec/packages/ec-component-table/demo/data--sort-table.js
- src/ec/packages/ec-component-table/ecl-table.html.twig
- src/ec/packages/ec-component-table/package.json
- src/ec/packages/ec-component-table/table.story.js
- src/ec/packages/ec-component-table/table.test.js
- yarn.lock
> feat(table): Adding sortable demo - front-1304

- php/php_storybook/resources/helpers.php
- php/php_storybook/resources/story-template.txt
- php/php_storybook/scripts/render.php
> feat(php-storybook): Converting the php generated story files to CSF - front-1379

- src/ec/packages/ec-component-hero-banner/hero-banner.story.js
- src/ec/packages/ec-component-pagination/__snapshots__/pagination.test.js.snap
- src/ec/packages/ec-component-pagination/adapter.js
- src/ec/packages/ec-component-pagination/demo/data.js
- src/ec/packages/ec-component-pagination/ecl-pagination.html.twig
- src/ec/packages/ec-component-pagination/pagination.story.js
> fix(pagination): Fixing markup for links without icons - front-1574

- src/ec/packages/ec-component-menu/README.md
- src/ec/packages/ec-component-menu/__snapshots__/menu.test.js.snap
- src/ec/packages/ec-component-menu/adapter.js
- src/ec/packages/ec-component-menu/ecl-menu-item.html.twig
- src/ec/packages/ec-component-menu/package.json
- yarn.lock
> feat(menu): Adding span for accessibiltiy - FRONT-1818

- src/ec/packages/ec-component-ecl-compliance/components/ecl-compliance-timeline.html.twig
- src/ec/packages/ec-component-timeline/README.md
- src/ec/packages/ec-component-timeline/__snapshots__/timeline.test.js.snap
- src/ec/packages/ec-component-timeline/ecl-timeline.html.twig
- src/ec/packages/ec-component-timeline/timeline.story.js
- src/ec/packages/ec-component-timeline/timeline.test.js
> feat(timeline): Content is optional and title mandatory - FRONT-2036
